### PR TITLE
Organize site directory

### PR DESCRIPTION
**Pull request by etefera**
Fixes https://github.com/GoogleContainerTools/kpt/issues/1678
Moves inline JS and CSS to separate static files.
Removes remaining hugo files.
Removes `node_modules` from the site's directory in the repo.

### CODE REVIEW

**Comment by mikebz** [comment]
what tests were performed to ensure that the site was not broken?  5000 file purge is hard to review so trying to make sure we do some before/after checks.

**Comment by etefera** [comment]
> what tests were performed to ensure that the site was not broken? 5000 file purge is hard to review so trying to make sure we do some before/after checks.

Manually ran locally and at https://kpt-dev-ee2a9--clean-site-dir-r3q5fcok.web.app/

**Review by mikebz — APPROVED** [review]

**Comment by mikebz** [comment]
Thank you.  Approving now but for large changes like that I'd recommend doing a few things:
1) different browser checks
2) pages that are different than other pages (maybe they have different widgets)
3) mobile rendering

Thank you!

**Comment by etefera** [comment]
> Thank you. Approving now but for large changes like that I'd recommend doing a few things:
> 
> 1. different browser checks
> 2. pages that are different than other pages (maybe they have different widgets)
> 3. mobile rendering
> 
> Thank you!

Ah yes, meant that 1&2 had happened both ran locally and in the above link

**Pull request merged**
