### PR TITLE
Oci support

### PR DESCRIPTION
**Pull request by loudej**
Adds OCI support for `kpt pkg get`

First PR of a small series to add OCI to an experimental kpt branch

### CODE REVIEW

**Comment by mikebz** [comment]
Hey @loudej we just launched a public design document template.  Could be good to describe how OCI will work in a way that's visible to the user base: https://github.com/GoogleContainerTools/kpt/blob/main/CONTRIBUTING.md

**Review by droot — COMMENTED** [review]
Thanks for the PR @loudej  

One thing I was wondering was if we could abstract out the pkg fetcher code such that we can have pkg fetcher implementation for GitPkgFetcher and OciPkgFetcher and we instantiate these as early as possible in the command life-cycle. This could avoid code having switch case for `Git` and `Oci`.

WDYT ?

**Comment by loudej** [comment]
Hi @mikebz Sounds like a great idea. As I understand the procedure - this idea is to have an additional PR that contains only a copy of the md and it should be in the same folder as the template?

@droot Sounds good - I'll take a look. I think I know what layer you're talking about (something to use just under the util/*/Command logic)

**Comment by mikebz** [comment]
Yes. What I have seen with other products is the same folder but maybe start with a different number. Thank you!

**Comment by loudej** [comment]
@droot Hi again! Well, there was already a `fetch` Command package and I was concerned `fetch` and `fetcher` would be very easy to confused. Instead I added an `upstream` package because all of the work will be dealing with the upstream sources and upstream/upstreamLock Kptfile properties. 

It has an`upstream.Fetcher` interface that duck types onto `upstream.gitUpstream` and `upstream.ociUpstream`. Let me know if that resonates with you or if the names should be shuffled around to something better.

Ah - the impact on the code is that it is cleaner, but it will make it harder to keep the branch in line with main.

**Comment by phanimarupaka** [comment]
I am looking forward to the design document, especially highlighting the user guide/journey for `get`, `update` and `diff` commands before I take a stab at reviewing the code.

**Comment by loudej** [comment]
@phanimarupaka sounds great, sorry for the delay! That is my next task on deck, and thanks for the help!

**Comment by loudej** [comment]
Added companion PR #2589 with design doc. Happy to iterate and collaborate on that, hoping it aligns with what you were expecting!

Also PR is smaller scope than design doc - it doesn't support sub-package or diff yet - and push/pull commands aren't added.

/cc @phanimarupaka @droot @mikebz

**Comment by loudej** [comment]
Closing this PR in favor of #2621 which is rebased on current main

**Pull request closed without merging**
