### PR TITLE
release: Generate SLSA signatures on GitHub releases

### PR DESCRIPTION
**Pull request by asraa**
Signed-off-by: Asra Ali <asraa@google.com>

Hi,

I'm reaching out on behalf of the [Open Source Security Foundation (openssf.org)](https://openssf.org/). We work on improving the security of critical open source projects like yours.

Together with [GitHub](https://github.blog/2022-04-07-slsa-3-compliance-with-github-actions/), we designed a free, easy-to-use method of code signing. It will help your users verify that your release binaries were built from your repository’s [workflow](https://github.com/GoogleContainerTools/kpt/blob/master/.github/workflows/release.yml) and not altered by anyone. It’s just a few lines of code, but it will make your project more secure against third-party tampering and attacks like [Codecov](https://about.codecov.io/apr-2021-post-mortem/) and [CTX](https://sockpuppets.medium.com/how-i-hacked-ctx-and-phpass-modules-656638c6ec5e).

We have also integrated with [jib](https://github.com/GoogleContainerTools/jib).

This PR shows how to add this seamless code signing to your workflow. You don’t have to be a cryptography expert or learn complicated tools and [verification](https://github.com/slsa-framework/slsa-verifier/blob/main/README.md#verification-of-provenance) is simple for your users.

You can read more on the [SLSA blog](https://slsa.dev/blog/2022/06/slsa-github-workflows) or on the documentation of the workflow [here](https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/generic/README.md). Please reach out if you have any questions!

### CODE REVIEW

**Comment by mortent** [comment]
@asraa Thanks for the contribution. It looks good to me.

**Comment by asraa** [comment]
Thank you! Are e2e test flakey? Not sure I can reproduce.

**Comment by mortent** [comment]
The tests failed due to timeouts, so might be something with the infrastructure. I'm re-running the tests

**Comment by mortent** [comment]
I've retried the tests several times, but it always seems to fail with the same tests. Not sure why, since these changes doesn't impact that in any way. Can you try to rebase the PR and see if that fixes it?

**Review by mortent — APPROVED** [review]

**Pull request merged**
