### PR TITLE
Add Github links to bottom of page.

### PR DESCRIPTION
**Pull request by etefera**
Fixes https://github.com/GoogleContainerTools/kpt/issues/1650
Demo at https://kpt-dev-ee2a9--gh-links-krrsgv3x.web.app/
image
image

### CODE REVIEW

**Comment by mikebz** [comment]
I think generally the feedback is at the bottom of the page with a button like this:
image

I would have two buttons: edit on github and submit an issue.  Is that possible?  Given that this is not a major theme in our documentation I'd probably just keep it to just icons - github icon for the deep link to the MD document and a bug icon 

image

https://fonts.gstatic.com/s/i/googlematerialicons/bug_report/v10/gm_grey-24dp/1x/gm_bug_report_gm_grey_24dp.png

**Comment by frankfarzan** [comment]
Looking good, one style comment: the icons are overpowering the Previous/Next buttons which are the happy path action to take. I would make them less prominent by adjusting color or opacity. Matching the style of Previous/Next is also looks cleaner.

**Comment by frankfarzan** [comment]
> Looking good, one style comment: the icons are overpowering the Previous/Next buttons which are the happy path action to take. I would make them less prominent by adjusting color or opacity. Matching the style of Previous/Next is also looks cleaner.

Alternatively, make Preivous/Next buttons more prominent by increasing their value.

**Comment by etefera** [comment]
> > Looking good, one style comment: the icons are overpowering the Previous/Next buttons which are the happy path action to take. I would make them less prominent by adjusting color or opacity. Matching the style of Previous/Next is also looks cleaner.
> 
> Alternatively, make Preivous/Next buttons more prominent by increasing their value.

Went with replicating the adjusting-opacity behavior of the buttons on hover.

**Review by frankfarzan — APPROVED** [review]
Looks very nice

**Pull request merged**
