### PR TITLE
Move internal/kptfile to pkg/kptfile to make it vendorable

### PR DESCRIPTION
**Pull request by barney-s**
Moving kptfile schema and utils under pkg to make it vendorable.

Planning to vendor KPTFile schema in another tool that parses kptfile and extracts metadata from it.

### CODE REVIEW

**Comment by barney-s** [comment]
Verified this on my tool. It works.

**Comment by mortent** [comment]
We are doing a release today. Let's hold off merging this until we have cut the release.

**Comment by seans3** [comment]
I think this looks good. Do we want to modify the current kptfile API, or is the current one sufficient? Once we start using the kptfile API outside of kpt, it will be much more difficult to change.

**Comment by barney-s** [comment]
Iam not blocked on this. We can merge later.
I forked and am iterating on the fork.

Regarding the API sufficiency, it is too early to comment.
I will review the API and see if we can move non-critical functions back into internal.
That we we can reduce the surface and only expose well defined ones.

Alternatively we could have a pkg/kptfile/beta file for non well defined ones.

**Review by mortent — APPROVED** [review]
This looks good to me. As Sean mentioned, we are still pre-1.0 so there almost certainly will be changes to the API.

**Pull request merged**
