### PR TITLE
Add initial outline of the kpt book

### PR DESCRIPTION
**Pull request by frankfarzan**
Rough outline of content for v1 guide as part of #1573

### CODE REVIEW

**Comment by frankfarzan** [comment]
@etefera This should give an idea of what we're looking for in #1574

**Comment by mikebz** [comment]
Question: if based on the user feedback we need to re-arrange the chapters what is your vision for updating that?  The URL changing is generally frowned upon for SEO purposes.  Other blogs and stackoverflow might be doing deep links to the chapters.

**Review by etefera — APPROVED** [review]
I like the {chapter}/{page} organization in this PR. It lends itself to simple pagination and generation of the sidebar. Speaking of which, the sidebar will be entirely replaced by the outline of the book, correct?

It's good to keep in mind that we have a lot of flexibility in the rendering of these pages and examples when they're siloed off like this as a book. Merging this in to experiment with such rendering for https://github.com/GoogleContainerTools/kpt/issues/1574 sounds good to me.

**Comment by frankfarzan** [comment]
@mikebz You're correct that in general changing the URL is type of a breaking change. I'm not sure there's a better answer besides: try to add chapters and pages (additive) instead of deleting (subtractive). One mitigating factor is remove the page title from the URL:

`kpt.dev/book/01-concepts/01-packages` -> `kpt.dev/book/01/01`

Which allows us to rename the chapters and pages (It should still be about "concept of package" and not a totally different content).

@etefera Something to think about when rendering these pages.

**Comment by frankfarzan** [comment]
> I like the {chapter}/{page} organization in this PR. It lends itself to simple pagination and generation of the sidebar. Speaking of which, the sidebar will be entirely replaced by the outline of the book, correct?

The book doesn't include such content as the command reference, contacts, faq. I think you're asking how does the navbar look when viewing the book? I think we can explore the options, but I think it makes sense to have navbar be only book content but have a backlink to top-level site somehow.




> 
> It's good to keep in mind that we have a lot of flexibility in the rendering of these pages and examples when they're siloed off like this as a book. Merging this in to experiment with such rendering for #1574 sounds good to me.

**Comment by etefera** [comment]
> > I like the {chapter}/{page} organization in this PR. It lends itself to simple pagination and generation of the sidebar. Speaking of which, the sidebar will be entirely replaced by the outline of the book, correct?
> 
> The book doesn't include such content as the command reference, contacts, faq. I think you're asking how does the navbar look when viewing the book? I think we can explore the options, but I think it makes sense to have the navbar show only the book outline but have a backlink to top-level site somehow.
> 
> > It's good to keep in mind that we have a lot of flexibility in the rendering of these pages and examples when they're siloed off like this as a book. Merging this in to experiment with such rendering for #1574 sounds good to me.

Yeah, that was my question. That approach (similar to what's planned for the function catalog) makes sense to me, too.

**Comment by etefera** [comment]
> @mikebz You're correct that in general changing the URL is type of a breaking change. I'm not sure there's a better answer besides: try to add chapters and pages (additive) instead of deleting (subtractive).
> 
> One mitigation may be to remove the page title from the URL:
> 
> `kpt.dev/book/01-concepts/01-packages` -> `kpt.dev/book/01/01`
> 
> Which allows us to rename the chapters and pages (It should still be about "concept of package" and not a totally different content).
> 
> @etefera Something to think about when rendering these pages.

It'd be nice to maintain the relationship between the path of the source markdown and the URL we present to users that has been consistent across the site so far. We should at least have high confidence in the chapter names/concepts for an outline like this. If that's the case, we can have `kpt.dev/book/concepts/01` representing the packages page above as well as the flexibility to change the ordering of the chapters and the content of the pages (at `/site/book/concepts/01.md` in this case) with minimal breakage.

**Comment by mikebz** [comment]
From what I know about Google SEO (which isn't much) I think it's best to keep the title of the page in the page URL.  So for instance if if we have a page for kpt packages it would be best to keep the url as something along the lines of kpt.dev/..../packages

**Comment by frankfarzan** [comment]
Let's follow discussion around URL in #1574

**Pull request merged**
