### PR TITLE
update pipeline e2e tests and enable docker tests in github actions

### LINKED ISSUE #1555: Enable

### PR DESCRIPTION
**Pull request by Shell32-Natsu**
Reorganize pipeline e2e tests and enable docker tests in CI.

Add diff of actual diff and expected diff to output when test fails.

close #1555

### CODE REVIEW

**Comment by frankfarzan** [comment]
looks good to me, I'll let others approve.

**Review by droot — APPROVED** [review]
Approving this PR because I need the changes in this PR for new test cases I am adding. We can address @mengqiy comments in a follow up PR (if any).

**Comment by mengqiy** [comment]
The code LGTM.
@Shell32-Natsu Can you please paste a example output when it dismatches? Trying to see the UX.

**Comment by Shell32-Natsu** [comment]
```diff
            Actual
            ===
            diff --git a/resources.yaml b/resources.yaml
            index 10cd18b..254b9cd 100644
            --- a/resources.yaml
            +++ b/resources.yaml
            @@ -11,11 +11,11 @@
             # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
             # See the License for the specific language governing permissions and
             # limitations under the License.
            -
             apiVersion: apps/v1
             kind: Deployment
             metadata:
               name: nginx-deployment
            +  namespace: staging
             spec:
               replicas: 3
             ---
            @@ -23,5 +23,6 @@ apiVersion: custom.io/v1
             kind: Custom
             metadata:
               name: custom
            +  namespace: staging
             spec:
               image: nginx:1.2.3
            Diff of Diff
            ===
            --- /tmp/kpt-e2e-diff-665531941/expected    2021-03-30 16:10:43.224505161 -0700
            +++ /tmp/kpt-e2e-diff-665531941/actual      2021-03-30 16:10:43.224505161 -0700
            @@ -1,8 +1,8 @@
             diff --git a/resources.yaml b/resources.yaml
            -index 10cd18b..c77c357 100644
            +index 10cd18b..254b9cd 100644
             --- a/resources.yaml
             +++ b/resources.yaml
            -@@ -11,17 +11,29 @@
            +@@ -11,11 +11,11 @@
              # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
              # See the License for the specific language governing permissions and
              # limitations under the License.
            @@ -10,25 +10,14 @@
              apiVersion: apps/v1
              kind: Deployment
              metadata:
            -+  labels:
            -+    tier: backend
                name: nginx-deployment
             +  namespace: staging
              spec:
                replicas: 3
            -+  selector:
            -+    matchLabels:
            -+      tier: backend
            -+  template:
            -+    metadata:
            -+      labels:
            -+        tier: backend
              ---
            - apiVersion: custom.io/v1
            +@@ -23,5 +23,6 @@ apiVersion: custom.io/v1
              kind: Custom
              metadata:
            -+  labels:
            -+    tier: backend
                name: custom
             +  namespace: staging
              spec:
```

It's not very easy to read since it's a diff of diff, but it makes difference easier to find.

**Pull request merged**
