### PR TITLE
Disable ensureSameOrigin

### PR DESCRIPTION
**Pull request by johnbelamaric**
During our testing in Nephio, we have found that `ensureSameOrigin` seems to erroneously flag updates as invalid, so I think we should disable it for now.

### CODE REVIEW

**Comment by mortent** [comment]
Do we know exactly what was causing the problem? I think the `ensureSameOrigin` logic had some potential problems and I'm less convinced about the usefulness of this than when we introduced it, but it would be helpful to understand exactly what happened.

**Comment by johnbelamaric** [comment]
No, not yet. I did add some logging; it showed that in the cases we're talking about, it fell through to the very last return statement.

I can try to capture a specific package that fails. Maybe we can fix it. I disabled it in the Nephio build to work around the problem, but I can spend a little more time on it now.

**Comment by johnbelamaric** [comment]
I added another package this happens with in #3980. But actually it seems to be happening with almost every package created via `clone`. If I clone it, I can't do a `copy`. I am wondering if we have an e2e test that does a clone-and-copy?

I think we probably want to merge this PR while we figure it out.

**Comment by johnbelamaric** [comment]
Ok, based on https://github.com/GoogleContainerTools/kpt/issues/3980#issuecomment-1627905588 I have removed the ensureSameOrigin altogether, and flipped the default for replay strategy.

**Comment by mortent** [comment]
This looks good to me. I also want to see if @natasha41575 has any input on this before we merge it.

**Comment by johnbelamaric** [comment]
May be a legit failure do to replay strategy flip, let me take a closer look.

**Comment by johnbelamaric** [comment]
Ok, yeah, fixed the legit failure and also fixed a flake in the PVS unit tests.

**Comment by mortent** [comment]
I think we've given enough time for feedback on this one, so I think we are good to merge it.

**Review by mortent — APPROVED** [review]

**Pull request merged**
