### PR TITLE
Use go 1.18

### PR DESCRIPTION
**Pull request by mortent**
This updates kpt and porch to use go 1.18.

### CODE REVIEW

**Review by droot — APPROVED** [review]
We will also have to update the docs where we list Go 1.17+ as the prerequisites (can be done as an immediate followup).

**Comment by mortent** [comment]
We'll hold off a little bit here since it impacts any downstream consumers of kpt.

**Comment by natasha41575** [comment]
qq, do we plan to switch to go workspace mode as well?

**Review by mengqiy — APPROVED** [review]

**Comment by mengqiy** [comment]
I needs golang 1.18+ in https://github.com/GoogleContainerTools/kpt/pull/3450.
```
# github.com/prep/wasmexec
Error: ../../../go/pkg/mod/github.com/prep/wasmexec@v0.0.0-20220807105708-6554945c1dec/js.go:12:34: undefined: any
Error: ../../../go/pkg/mod/github.com/prep/wasmexec@v0.0.0-20220807105708-6554945c1dec/js.go:40:19: undefined: any
Error: ../../../go/pkg/mod/github.com/prep/wasmexec@v0.0.0-20220807105708-6554945c1dec/js.go:44:35: undefined: any
Error: ../../../go/pkg/mod/github.com/prep/wasmexec@v0.0.0-20220807105708-6554945c1dec/js.go:55:30: undefined: any
Error: ../../../go/pkg/mod/github.com/prep/wasmexec@v0.0.0-20220807105708-6554945c1dec/js.go:64:13: undefined: any
Error: ../../../go/pkg/mod/github.com/prep/wasmexec@v0.0.0-20220807105708-6554945c1dec/module.go:34:33: undefined: any
Error: ../../../go/pkg/mod/github.com/prep/wasmexec@v0.0.0-20220807105708-6554945c1dec/module.go:39:33: undefined: any
Error: ../../../go/pkg/mod/github.com/prep/wasmexec@v0.0.0-20220807105708-6554945c1dec/module.go:70:16: undefined: any
Error: ../../../go/pkg/mod/github.com/prep/wasmexec@v0.0.0-20220807105708-6554945c1dec/module.go:71:23: undefined: any
Error: ../../../go/pkg/mod/github.com/prep/wasmexec@v0.0.0-20220807105708-6554945c1dec/module.go:425:46: undefined: any
Error: ../../../go/pkg/mod/github.com/prep/wasmexec@v0.0.0-20220807105708-6554945c1dec/module.go:425:46: too many errors
note: module requires Go 1.18
```

**Comment by mortent** [comment]
Updated the PR to switch to 1.18 instead of 1.19. Got feedback that forcing downstream consumers to switch to the absolute latest version could be problematic. As far as I know we don't have a strong reason to prefer 1.19 over 1.18.

@droot @mengqiy 

@natasha41575 We can use go workspaces, but we need to figure out how to be use it. Not sure if it will work well to check the workspace file into git.

**Review by mengqiy — APPROVED** [review]
LGTM

**Pull request merged**
