### PR TITLE
docs: Hide outdated guides

### PR DESCRIPTION
**Pull request by mortent**
It is unclear if the blueprint guide is still aligned with the direction of kpt, so this PR hides it. It also hides the variants guide since it doesn't have any content.

### CODE REVIEW

**Review by prachirp — APPROVED** [review]
LGTM, I learned about the draft field.

**Comment by frankfarzan** [comment]
I suggest just deleting it. Git history is sufficient to revive it if necessary.

**Comment by mortent** [comment]
@frankfarzan updated

**Review by frankfarzan — APPROVED** [review]

**Pull request merged**
