### PR TITLE
Run Porch as non-root

### PR DESCRIPTION
**Pull request by adetalhouet**
Create a `porch` user to run the porch-server as non-root.

### CODE REVIEW

**Comment by johnbelamaric** [comment]
@adetalhouet you probably need to make similar changes to the deployment manifests produced by the Porch build process as you did in the Nephio repo. The manifests in the Nephio repo are just a subset of the ones generated here.

Right now, e2e tests are failing, likely because the manifests used to install Porch [here](https://github.com/GoogleContainerTools/kpt/actions/runs/5943534760/job/16159443837?pr=4028#step:8:15) do not have those changes.

**Review by johnbelamaric — APPROVED** [review]

**Comment by johnbelamaric** [comment]
cc @mortent @natasha41575

**Review by natasha41575 — APPROVED** [review]
the change itself LGTM and I think it makes sense to do this, but I think we should make sure @mortent agrees before merging

**Review by mortent — APPROVED** [review]
Looks good. Thanks for the contribution @adetalhouet

**Pull request merged**
