### PR TITLE
Add kubeconfig flags to relevant live cmds.

### LINKED ISSUE #455: The --context flag is not implemented
When running `kpt live --help`, it mentions:

```
      --cluster string                 The name of the kubeconfig cluster to use
      --context string                 The name of the kubeconfig context to use
```

However:

```
$ kpt live apply --context=foo dir
Error: unknown flag: --context
$ kpt live --context=foo apply dir
Error: unknown flag: --context
```

I'd triage this as a bug as opposed to a feature request :)

### PR DESCRIPTION
**Pull request by bzub**
Fixes #455

### CODE REVIEW

**Comment by bzub** [comment]
@googlebot I signed it!

**Comment by seans3** [comment]
Do we want to do this in `cli-utils` or do we want to do it here?

**Comment by mortent** [comment]
I think we would like to make this change in https://github.com/kubernetes-sigs/cli-utils rather than here. All the other flags are defined there, so it seems to make the most sense.
@bzub would you be willing to move this to a PR against cli-utils?

**Comment by bzub** [comment]
@mortent Yup will do.

**Comment by pwittrock** [comment]
@bzub thanks!

**Comment by seans3** [comment]
Actually, now that I look at it, I think your original approach in `kpt live` makes more sense than `cli-utils`--reopening.

/reopen

**Comment by seans3** [comment]
For more context, the kubeconfig flags are created in `kpt live` -- not `cli-utils`. And the fix is to use `persistent flags` to persist to the flags to the subcommands (they exist on `kpt live`, but not `kpt live <subcommand>`. So we should perform the fix in `kpt`. Although it looks I don't have permissions to reopen this PR.

/cc @mortent

**Pull request closed without merging**
