### PR TITLE
Update to cli-utils v0.29.1

### PR DESCRIPTION
**Pull request by karlkfi**
Highlights:
- Dependencies are now enforced by skipping actuation of dependents
  when one of their dependencies failed actuation or reconciliation.
- DaemonSets are no longer considered immediately reconciled until
  after the controller has set status.observedGeneration.

### CODE REVIEW

**Comment by karlkfi** [comment]
Updated the porch submodules. Apparently you have to run `make -C porch fix-all` now to propagate go.mod changes.

**Comment by karlkfi** [comment]
/hold

Looks like I broke --dry-run when it includes a dependency. I'll have to patch that in cli-utils

**Comment by karlkfi** [comment]
```
kpt live apply --dry-run e2e/live/testdata/rg-test-case-1a
Dry-run strategy: client
namespace/rg-test-namespace created
pod/pod-a apply failed: premature apply: dependency apply reconcile pending: "_rg-test-namespace__Namespace"
pod/pod-b apply failed: premature apply: dependency apply reconcile pending: "_rg-test-namespace__Namespace"
pod/pod-c apply failed: premature apply: dependency apply reconcile pending: "_rg-test-namespace__Namespace"
4 resource(s) applied. 1 created, 0 unchanged, 0 configured, 3 failed
3 resources failed 
```

**Review by droot — APPROVED** [review]

**Comment by droot** [comment]
> ```
> kpt live apply --dry-run e2e/live/testdata/rg-test-case-1a
> Dry-run strategy: client
> namespace/rg-test-namespace created
> pod/pod-a apply failed: premature apply: dependency apply reconcile pending: "_rg-test-namespace__Namespace"
> pod/pod-b apply failed: premature apply: dependency apply reconcile pending: "_rg-test-namespace__Namespace"
> pod/pod-c apply failed: premature apply: dependency apply reconcile pending: "_rg-test-namespace__Namespace"
> 4 resource(s) applied. 1 created, 0 unchanged, 0 configured, 3 failed
> 3 resources failed 
> ```
> 
> The problem is that the status isn't being updated after apply when dry-run is enabled, so the new dependency filter thinks the status is invalid and errors.

@karlkfi so what's the plan ?

**Comment by karlkfi** [comment]
I'm working on a PR in cli-utils to fix it and will make a v0.29.1 release and then update this PR.

**Comment by karlkfi** [comment]
Should be fixed by https://github.com/kubernetes-sigs/cli-utils/pull/558

Once it merges, I'll tag v0.29.1

**Comment by karlkfi** [comment]
Updated this PR to cli-utils v0.29.1

**Comment by karlkfi** [comment]
All tests passed. I think we're good to go.

**Review by mortent — APPROVED** [review]

**Pull request merged**
