### PR TITLE
Clean up demo videos.

### PR DESCRIPTION
**Pull request by etefera**
Fixes https://github.com/GoogleContainerTools/kpt/issues/1654

### CODE REVIEW

**Comment by mikebz** [comment]
when I press play the video resizes.

**Comment by etefera** [comment]
> when I press play the video resizes.

Addressed and the demo has been updated.

**Comment by mikebz** [comment]
LGTM

**Comment by mortent** [comment]
The video looks good to me. Do we have a way to run e2e tests on the original script for the video so we can make sure it doesn't become stale? We can do that separately, but we should probably keep the original issue open until we have that in place.

**Comment by etefera** [comment]
> The video looks good to me. Do we have a way to run e2e tests on the original script for the video so we can make sure it doesn't become stale? We can do that separately, but we should probably keep the original issue open until we have that in place.

No tests for the script yet but I do agree that should be tracked. It should probably be in a different issue, however, tracking an enhancement for these casts.

**Comment by frankfarzan** [comment]
preview page doesn't work.

**Comment by etefera** [comment]
> preview page doesn't work.

Updated URL.

**Review by mortent — APPROVED** [review]

**Comment by frankfarzan** [comment]
Several issues:
1. https://screenshot.googleplex.com/4F8bwgMjVYHWXSK
2. IMO, The video is too long and slow. Some suggestions:
   - We don't need to demo the entire quick start guide
   - Speed up playback speed
3. Consider moving into a separate page with a call-to-action link from the overview

**Comment by frankfarzan** [comment]
FYI, this is not a high priority issue (it's an good-to-have M4), so don't spend too much time on it in M3.

**Comment by mikebz** [comment]
can we merge what we have and just create an issue for other follow ups or keep this issue open?

**Comment by frankfarzan** [comment]
This requires more work, IMO it's not emphasizing the right aspects. e.g.:
- render is missing
- we're not showing the Kptfile pipeline
- eval is glossed over
- etc.

Given it's not a blocker, I suggest putting the issue on the backlog.

**Comment by mikebz** [comment]
can we just merge this and iterate?

**Comment by frankfarzan** [comment]
This is a good-to-have so we don't need to rush it before addressing the comments.

**Comment by etefera** [comment]
Reopening and changing scope to just deleting unused videos.

**Review by droot — APPROVED** [review]

**Pull request merged**
