### PR TITLE
Remove sync command from next

### PR DESCRIPTION
**Pull request by phanimarupaka**
This PR removes the sync functionality from next branch which is being replaced by update command.

Fixes: https://github.com/GoogleContainerTools/kpt/issues/1434

### CODE REVIEW

**Review by mortent — APPROVED** [review]

**Review by frankfarzan — CHANGES_REQUESTED** [review]
Do we have open issues for final 'kpt update' behavior? One thing recently discussed, if there's no `upstreamLock` field defined, then `kpt pkg update` should only fetch the subpackages, you don't need `--only-subpackages` flag.

**Comment by phanimarupaka** [comment]
@frankfarzan What changes are you expecting in this PR?

**Comment by mortent** [comment]
I think there are issues for most of the remaining work. The main functionality to replace the `sync` command is already done.

I think we still want the `--only-subpackages` flag on the `kpt pkg update` command to allow users to update only the subpackages without forcing them to also update the parent package.

**Comment by frankfarzan** [comment]
> I think there are issues for most of the remaining work. The main functionality to replace the `sync` command is already done.
> 
> I think we still want the `--only-subpackages` flag on the `kpt pkg update` command to allow users to update only the subpackages without forcing them to also update the parent package.

To clarify: If there's no upstream, then specifying that flag should be optional, with the default behavior working as expected.

**Comment by frankfarzan** [comment]
Is this ready for review? If so, please add me back.

**Comment by phanimarupaka** [comment]
This PR was changes were already part of other PRs and merged.

**Pull request closed without merging**
